name: pdf_editor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  intl: ^0.19.0
  go_router: ^15.1.3
  connectivity_plus: ^6.1.4
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  share_plus: ^10.1.4
  printing: ^5.14.2
  local_auth: ^2.3.0 # face id
  url_launcher: ^6.3.1
  # syncfusion
  syncfusion_flutter_pdf: ^29.2.11
  # db
  sqflite: ^2.4.2
  path: ^1.9.1
  # vip
  purchases_flutter: ^8.10.2
  purchases_ui_flutter: ^8.10.2
  #
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: w400
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: w500
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/Roboto-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
