name: pdf_editor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  intl: ^0.19.0
  go_router: ^15.1.3
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  share_plus: ^10.1.4
  printing: ^5.14.2
  local_auth: ^2.3.0 # face id
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.2.1
  cunning_document_scanner: ^1.2.3
  camera: ^0.11.1
  syncfusion_flutter_pdfviewer: ^30.1.37
  syncfusion_flutter_pdf: ^30.1.39
  docx_to_text: ^1.0.1 # docx to text
  pdf: ^3.11.3
  screenshot: ^3.0.0
  nextgen_pdf_editor:
    path: ./packages/nextgen_pdf_editor
  # qr_code_scanner: ^1.0.1
  # pdf_render: ^1.4.12
  # pdf_combiner: ^4.3.5 # image to pdf | pdf to images | combine pdfs
  purchases_flutter: ^8.10.2
  purchases_ui_flutter: ^8.10.2
  pdf_render: ^1.4.12
  #
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: w400
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: w500
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/Roboto-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
